/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClerkRouteRouteImport } from './routes/clerk/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as ClerkAuthenticatedRouteRouteImport } from './routes/clerk/_authenticated/route'
import { Route as ClerkauthRouteRouteImport } from './routes/clerk/(auth)/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedAccountRouteRouteImport } from './routes/_authenticated/account/route'
import { Route as AuthenticatedVerificationsIndexRouteImport } from './routes/_authenticated/verifications/index'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedReviewsIndexRouteImport } from './routes/_authenticated/reviews/index'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports/index'
import { Route as AuthenticatedPlatformSettingsIndexRouteImport } from './routes/_authenticated/platform-settings/index'
import { Route as AuthenticatedJobPostsIndexRouteImport } from './routes/_authenticated/job-posts/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedChatLogsIndexRouteImport } from './routes/_authenticated/chat-logs/index'
import { Route as AuthenticatedBookingsIndexRouteImport } from './routes/_authenticated/bookings/index'
import { Route as AuthenticatedAuditLogsIndexRouteImport } from './routes/_authenticated/audit-logs/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as AuthenticatedAccountIndexRouteImport } from './routes/_authenticated/account/index'
import { Route as ClerkAuthenticatedUserManagementRouteImport } from './routes/clerk/_authenticated/user-management'
import { Route as ClerkauthSignUpRouteImport } from './routes/clerk/(auth)/sign-up'
import { Route as ClerkauthSignInRouteImport } from './routes/clerk/(auth)/sign-in'
import { Route as AuthenticatedVerificationsIdRouteImport } from './routes/_authenticated/verifications/$id'
import { Route as AuthenticatedUsersIdRouteImport } from './routes/_authenticated/users/$id'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedReviewsIdRouteImport } from './routes/_authenticated/reviews/$id'
import { Route as AuthenticatedReportsIdRouteImport } from './routes/_authenticated/reports/$id'
import { Route as AuthenticatedPlatformSettingsServiceCategoriesRouteImport } from './routes/_authenticated/platform-settings/service-categories'
import { Route as AuthenticatedPlatformSettingsReportReasonsRouteImport } from './routes/_authenticated/platform-settings/report-reasons'
import { Route as AuthenticatedPlatformSettingsNotificationTemplatesRouteImport } from './routes/_authenticated/platform-settings/notification-templates'
import { Route as AuthenticatedPlatformSettingsAnnouncementsRouteImport } from './routes/_authenticated/platform-settings/announcements'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedChatLogsIdRouteImport } from './routes/_authenticated/chat-logs/$id'
import { Route as AuthenticatedBookingsIdRouteImport } from './routes/_authenticated/bookings/$id'
import { Route as AuthenticatedAccountSecurityRouteImport } from './routes/_authenticated/account/security'
import { Route as AuthenticatedAccountLoginActivityRouteImport } from './routes/_authenticated/account/login-activity'

const ClerkRouteRoute = ClerkRouteRouteImport.update({
  id: '/clerk',
  path: '/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkAuthenticatedRouteRoute = ClerkAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const ClerkauthRouteRoute = ClerkauthRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAccountRouteRoute =
  AuthenticatedAccountRouteRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedVerificationsIndexRoute =
  AuthenticatedVerificationsIndexRouteImport.update({
    id: '/verifications/',
    path: '/verifications/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedReviewsIndexRoute =
  AuthenticatedReviewsIndexRouteImport.update({
    id: '/reviews/',
    path: '/reviews/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlatformSettingsIndexRoute =
  AuthenticatedPlatformSettingsIndexRouteImport.update({
    id: '/platform-settings/',
    path: '/platform-settings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJobPostsIndexRoute =
  AuthenticatedJobPostsIndexRouteImport.update({
    id: '/job-posts/',
    path: '/job-posts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatLogsIndexRoute =
  AuthenticatedChatLogsIndexRouteImport.update({
    id: '/chat-logs/',
    path: '/chat-logs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBookingsIndexRoute =
  AuthenticatedBookingsIndexRouteImport.update({
    id: '/bookings/',
    path: '/bookings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAuditLogsIndexRoute =
  AuthenticatedAuditLogsIndexRouteImport.update({
    id: '/audit-logs/',
    path: '/audit-logs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountIndexRoute =
  AuthenticatedAccountIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAccountRouteRoute,
  } as any)
const ClerkAuthenticatedUserManagementRoute =
  ClerkAuthenticatedUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => ClerkAuthenticatedRouteRoute,
  } as any)
const ClerkauthSignUpRoute = ClerkauthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const ClerkauthSignInRoute = ClerkauthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const AuthenticatedVerificationsIdRoute =
  AuthenticatedVerificationsIdRouteImport.update({
    id: '/verifications/$id',
    path: '/verifications/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIdRoute = AuthenticatedUsersIdRouteImport.update({
  id: '/users/$id',
  path: '/users/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedReviewsIdRoute = AuthenticatedReviewsIdRouteImport.update({
  id: '/reviews/$id',
  path: '/reviews/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsIdRoute = AuthenticatedReportsIdRouteImport.update({
  id: '/reports/$id',
  path: '/reports/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlatformSettingsServiceCategoriesRoute =
  AuthenticatedPlatformSettingsServiceCategoriesRouteImport.update({
    id: '/platform-settings/service-categories',
    path: '/platform-settings/service-categories',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlatformSettingsReportReasonsRoute =
  AuthenticatedPlatformSettingsReportReasonsRouteImport.update({
    id: '/platform-settings/report-reasons',
    path: '/platform-settings/report-reasons',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlatformSettingsNotificationTemplatesRoute =
  AuthenticatedPlatformSettingsNotificationTemplatesRouteImport.update({
    id: '/platform-settings/notification-templates',
    path: '/platform-settings/notification-templates',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPlatformSettingsAnnouncementsRoute =
  AuthenticatedPlatformSettingsAnnouncementsRouteImport.update({
    id: '/platform-settings/announcements',
    path: '/platform-settings/announcements',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatLogsIdRoute = AuthenticatedChatLogsIdRouteImport.update({
  id: '/chat-logs/$id',
  path: '/chat-logs/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBookingsIdRoute = AuthenticatedBookingsIdRouteImport.update({
  id: '/bookings/$id',
  path: '/bookings/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountSecurityRoute =
  AuthenticatedAccountSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => AuthenticatedAccountRouteRoute,
  } as any)
const AuthenticatedAccountLoginActivityRoute =
  AuthenticatedAccountLoginActivityRouteImport.update({
    id: '/login-activity',
    path: '/login-activity',
    getParentRoute: () => AuthenticatedAccountRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/account': typeof AuthenticatedAccountRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/otp': typeof authOtpRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/account/login-activity': typeof AuthenticatedAccountLoginActivityRoute
  '/account/security': typeof AuthenticatedAccountSecurityRoute
  '/bookings/$id': typeof AuthenticatedBookingsIdRoute
  '/chat-logs/$id': typeof AuthenticatedChatLogsIdRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/platform-settings/announcements': typeof AuthenticatedPlatformSettingsAnnouncementsRoute
  '/platform-settings/notification-templates': typeof AuthenticatedPlatformSettingsNotificationTemplatesRoute
  '/platform-settings/report-reasons': typeof AuthenticatedPlatformSettingsReportReasonsRoute
  '/platform-settings/service-categories': typeof AuthenticatedPlatformSettingsServiceCategoriesRoute
  '/reports/$id': typeof AuthenticatedReportsIdRoute
  '/reviews/$id': typeof AuthenticatedReviewsIdRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/users/$id': typeof AuthenticatedUsersIdRoute
  '/verifications/$id': typeof AuthenticatedVerificationsIdRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/account/': typeof AuthenticatedAccountIndexRoute
  '/apps/': typeof AuthenticatedAppsIndexRoute
  '/audit-logs/': typeof AuthenticatedAuditLogsIndexRoute
  '/bookings/': typeof AuthenticatedBookingsIndexRoute
  '/chat-logs/': typeof AuthenticatedChatLogsIndexRoute
  '/chats/': typeof AuthenticatedChatsIndexRoute
  '/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/job-posts/': typeof AuthenticatedJobPostsIndexRoute
  '/platform-settings/': typeof AuthenticatedPlatformSettingsIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/reviews/': typeof AuthenticatedReviewsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tasks/': typeof AuthenticatedTasksIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/verifications/': typeof AuthenticatedVerificationsIndexRoute
}
export interface FileRoutesByTo {
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/login': typeof authLoginRoute
  '/otp': typeof authOtpRoute
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/account/login-activity': typeof AuthenticatedAccountLoginActivityRoute
  '/account/security': typeof AuthenticatedAccountSecurityRoute
  '/bookings/$id': typeof AuthenticatedBookingsIdRoute
  '/chat-logs/$id': typeof AuthenticatedChatLogsIdRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/platform-settings/announcements': typeof AuthenticatedPlatformSettingsAnnouncementsRoute
  '/platform-settings/notification-templates': typeof AuthenticatedPlatformSettingsNotificationTemplatesRoute
  '/platform-settings/report-reasons': typeof AuthenticatedPlatformSettingsReportReasonsRoute
  '/platform-settings/service-categories': typeof AuthenticatedPlatformSettingsServiceCategoriesRoute
  '/reports/$id': typeof AuthenticatedReportsIdRoute
  '/reviews/$id': typeof AuthenticatedReviewsIdRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/users/$id': typeof AuthenticatedUsersIdRoute
  '/verifications/$id': typeof AuthenticatedVerificationsIdRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/account': typeof AuthenticatedAccountIndexRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/audit-logs': typeof AuthenticatedAuditLogsIndexRoute
  '/bookings': typeof AuthenticatedBookingsIndexRoute
  '/chat-logs': typeof AuthenticatedChatLogsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/job-posts': typeof AuthenticatedJobPostsIndexRoute
  '/platform-settings': typeof AuthenticatedPlatformSettingsIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/reviews': typeof AuthenticatedReviewsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/verifications': typeof AuthenticatedVerificationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/clerk': typeof ClerkRouteRouteWithChildren
  '/_authenticated/account': typeof AuthenticatedAccountRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/clerk/(auth)': typeof ClerkauthRouteRouteWithChildren
  '/clerk/_authenticated': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/account/login-activity': typeof AuthenticatedAccountLoginActivityRoute
  '/_authenticated/account/security': typeof AuthenticatedAccountSecurityRoute
  '/_authenticated/bookings/$id': typeof AuthenticatedBookingsIdRoute
  '/_authenticated/chat-logs/$id': typeof AuthenticatedChatLogsIdRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/platform-settings/announcements': typeof AuthenticatedPlatformSettingsAnnouncementsRoute
  '/_authenticated/platform-settings/notification-templates': typeof AuthenticatedPlatformSettingsNotificationTemplatesRoute
  '/_authenticated/platform-settings/report-reasons': typeof AuthenticatedPlatformSettingsReportReasonsRoute
  '/_authenticated/platform-settings/service-categories': typeof AuthenticatedPlatformSettingsServiceCategoriesRoute
  '/_authenticated/reports/$id': typeof AuthenticatedReportsIdRoute
  '/_authenticated/reviews/$id': typeof AuthenticatedReviewsIdRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/users/$id': typeof AuthenticatedUsersIdRoute
  '/_authenticated/verifications/$id': typeof AuthenticatedVerificationsIdRoute
  '/clerk/(auth)/sign-in': typeof ClerkauthSignInRoute
  '/clerk/(auth)/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/_authenticated/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/_authenticated/account/': typeof AuthenticatedAccountIndexRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/audit-logs/': typeof AuthenticatedAuditLogsIndexRoute
  '/_authenticated/bookings/': typeof AuthenticatedBookingsIndexRoute
  '/_authenticated/chat-logs/': typeof AuthenticatedChatLogsIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/job-posts/': typeof AuthenticatedJobPostsIndexRoute
  '/_authenticated/platform-settings/': typeof AuthenticatedPlatformSettingsIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/reviews/': typeof AuthenticatedReviewsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/verifications/': typeof AuthenticatedVerificationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clerk'
    | '/account'
    | '/settings'
    | '/forgot-password'
    | '/login'
    | '/otp'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/account/login-activity'
    | '/account/security'
    | '/bookings/$id'
    | '/chat-logs/$id'
    | '/errors/$error'
    | '/platform-settings/announcements'
    | '/platform-settings/notification-templates'
    | '/platform-settings/report-reasons'
    | '/platform-settings/service-categories'
    | '/reports/$id'
    | '/reviews/$id'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/users/$id'
    | '/verifications/$id'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/account/'
    | '/apps/'
    | '/audit-logs/'
    | '/bookings/'
    | '/chat-logs/'
    | '/chats/'
    | '/help-center/'
    | '/job-posts/'
    | '/platform-settings/'
    | '/reports/'
    | '/reviews/'
    | '/settings/'
    | '/tasks/'
    | '/users/'
    | '/verifications/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/clerk'
    | '/forgot-password'
    | '/login'
    | '/otp'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/account/login-activity'
    | '/account/security'
    | '/bookings/$id'
    | '/chat-logs/$id'
    | '/errors/$error'
    | '/platform-settings/announcements'
    | '/platform-settings/notification-templates'
    | '/platform-settings/report-reasons'
    | '/platform-settings/service-categories'
    | '/reports/$id'
    | '/reviews/$id'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/users/$id'
    | '/verifications/$id'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/account'
    | '/apps'
    | '/audit-logs'
    | '/bookings'
    | '/chat-logs'
    | '/chats'
    | '/help-center'
    | '/job-posts'
    | '/platform-settings'
    | '/reports'
    | '/reviews'
    | '/settings'
    | '/tasks'
    | '/users'
    | '/verifications'
  id:
    | '__root__'
    | '/_authenticated'
    | '/clerk'
    | '/_authenticated/account'
    | '/_authenticated/settings'
    | '/clerk/(auth)'
    | '/clerk/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/login'
    | '/(auth)/otp'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/account/login-activity'
    | '/_authenticated/account/security'
    | '/_authenticated/bookings/$id'
    | '/_authenticated/chat-logs/$id'
    | '/_authenticated/errors/$error'
    | '/_authenticated/platform-settings/announcements'
    | '/_authenticated/platform-settings/notification-templates'
    | '/_authenticated/platform-settings/report-reasons'
    | '/_authenticated/platform-settings/service-categories'
    | '/_authenticated/reports/$id'
    | '/_authenticated/reviews/$id'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/users/$id'
    | '/_authenticated/verifications/$id'
    | '/clerk/(auth)/sign-in'
    | '/clerk/(auth)/sign-up'
    | '/clerk/_authenticated/user-management'
    | '/_authenticated/account/'
    | '/_authenticated/apps/'
    | '/_authenticated/audit-logs/'
    | '/_authenticated/bookings/'
    | '/_authenticated/chat-logs/'
    | '/_authenticated/chats/'
    | '/_authenticated/help-center/'
    | '/_authenticated/job-posts/'
    | '/_authenticated/platform-settings/'
    | '/_authenticated/reports/'
    | '/_authenticated/reviews/'
    | '/_authenticated/settings/'
    | '/_authenticated/tasks/'
    | '/_authenticated/users/'
    | '/_authenticated/verifications/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ClerkRouteRoute: typeof ClerkRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authLoginRoute: typeof authLoginRoute
  authOtpRoute: typeof authOtpRoute
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/clerk': {
      id: '/clerk'
      path: '/clerk'
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk/_authenticated': {
      id: '/clerk/_authenticated'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkAuthenticatedRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/clerk/(auth)': {
      id: '/clerk/(auth)'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkauthRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/verifications/': {
      id: '/_authenticated/verifications/'
      path: '/verifications'
      fullPath: '/verifications/'
      preLoaderRoute: typeof AuthenticatedVerificationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/reviews/': {
      id: '/_authenticated/reviews/'
      path: '/reviews'
      fullPath: '/reviews/'
      preLoaderRoute: typeof AuthenticatedReviewsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform-settings/': {
      id: '/_authenticated/platform-settings/'
      path: '/platform-settings'
      fullPath: '/platform-settings/'
      preLoaderRoute: typeof AuthenticatedPlatformSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/job-posts/': {
      id: '/_authenticated/job-posts/'
      path: '/job-posts'
      fullPath: '/job-posts/'
      preLoaderRoute: typeof AuthenticatedJobPostsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center/'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat-logs/': {
      id: '/_authenticated/chat-logs/'
      path: '/chat-logs'
      fullPath: '/chat-logs/'
      preLoaderRoute: typeof AuthenticatedChatLogsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bookings/': {
      id: '/_authenticated/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof AuthenticatedBookingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/audit-logs/': {
      id: '/_authenticated/audit-logs/'
      path: '/audit-logs'
      fullPath: '/audit-logs/'
      preLoaderRoute: typeof AuthenticatedAuditLogsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account/': {
      id: '/_authenticated/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AuthenticatedAccountIndexRouteImport
      parentRoute: typeof AuthenticatedAccountRouteRoute
    }
    '/clerk/_authenticated/user-management': {
      id: '/clerk/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/clerk/user-management'
      preLoaderRoute: typeof ClerkAuthenticatedUserManagementRouteImport
      parentRoute: typeof ClerkAuthenticatedRouteRoute
    }
    '/clerk/(auth)/sign-up': {
      id: '/clerk/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/clerk/sign-up'
      preLoaderRoute: typeof ClerkauthSignUpRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/clerk/(auth)/sign-in': {
      id: '/clerk/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/clerk/sign-in'
      preLoaderRoute: typeof ClerkauthSignInRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/_authenticated/verifications/$id': {
      id: '/_authenticated/verifications/$id'
      path: '/verifications/$id'
      fullPath: '/verifications/$id'
      preLoaderRoute: typeof AuthenticatedVerificationsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/$id': {
      id: '/_authenticated/users/$id'
      path: '/users/$id'
      fullPath: '/users/$id'
      preLoaderRoute: typeof AuthenticatedUsersIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/reviews/$id': {
      id: '/_authenticated/reviews/$id'
      path: '/reviews/$id'
      fullPath: '/reviews/$id'
      preLoaderRoute: typeof AuthenticatedReviewsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports/$id': {
      id: '/_authenticated/reports/$id'
      path: '/reports/$id'
      fullPath: '/reports/$id'
      preLoaderRoute: typeof AuthenticatedReportsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform-settings/service-categories': {
      id: '/_authenticated/platform-settings/service-categories'
      path: '/platform-settings/service-categories'
      fullPath: '/platform-settings/service-categories'
      preLoaderRoute: typeof AuthenticatedPlatformSettingsServiceCategoriesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform-settings/report-reasons': {
      id: '/_authenticated/platform-settings/report-reasons'
      path: '/platform-settings/report-reasons'
      fullPath: '/platform-settings/report-reasons'
      preLoaderRoute: typeof AuthenticatedPlatformSettingsReportReasonsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform-settings/notification-templates': {
      id: '/_authenticated/platform-settings/notification-templates'
      path: '/platform-settings/notification-templates'
      fullPath: '/platform-settings/notification-templates'
      preLoaderRoute: typeof AuthenticatedPlatformSettingsNotificationTemplatesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/platform-settings/announcements': {
      id: '/_authenticated/platform-settings/announcements'
      path: '/platform-settings/announcements'
      fullPath: '/platform-settings/announcements'
      preLoaderRoute: typeof AuthenticatedPlatformSettingsAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat-logs/$id': {
      id: '/_authenticated/chat-logs/$id'
      path: '/chat-logs/$id'
      fullPath: '/chat-logs/$id'
      preLoaderRoute: typeof AuthenticatedChatLogsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/bookings/$id': {
      id: '/_authenticated/bookings/$id'
      path: '/bookings/$id'
      fullPath: '/bookings/$id'
      preLoaderRoute: typeof AuthenticatedBookingsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account/security': {
      id: '/_authenticated/account/security'
      path: '/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof AuthenticatedAccountSecurityRouteImport
      parentRoute: typeof AuthenticatedAccountRouteRoute
    }
    '/_authenticated/account/login-activity': {
      id: '/_authenticated/account/login-activity'
      path: '/login-activity'
      fullPath: '/account/login-activity'
      preLoaderRoute: typeof AuthenticatedAccountLoginActivityRouteImport
      parentRoute: typeof AuthenticatedAccountRouteRoute
    }
  }
}

interface AuthenticatedAccountRouteRouteChildren {
  AuthenticatedAccountLoginActivityRoute: typeof AuthenticatedAccountLoginActivityRoute
  AuthenticatedAccountSecurityRoute: typeof AuthenticatedAccountSecurityRoute
  AuthenticatedAccountIndexRoute: typeof AuthenticatedAccountIndexRoute
}

const AuthenticatedAccountRouteRouteChildren: AuthenticatedAccountRouteRouteChildren =
  {
    AuthenticatedAccountLoginActivityRoute:
      AuthenticatedAccountLoginActivityRoute,
    AuthenticatedAccountSecurityRoute: AuthenticatedAccountSecurityRoute,
    AuthenticatedAccountIndexRoute: AuthenticatedAccountIndexRoute,
  }

const AuthenticatedAccountRouteRouteWithChildren =
  AuthenticatedAccountRouteRoute._addFileChildren(
    AuthenticatedAccountRouteRouteChildren,
  )

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRouteRoute: typeof AuthenticatedAccountRouteRouteWithChildren
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedBookingsIdRoute: typeof AuthenticatedBookingsIdRoute
  AuthenticatedChatLogsIdRoute: typeof AuthenticatedChatLogsIdRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedPlatformSettingsAnnouncementsRoute: typeof AuthenticatedPlatformSettingsAnnouncementsRoute
  AuthenticatedPlatformSettingsNotificationTemplatesRoute: typeof AuthenticatedPlatformSettingsNotificationTemplatesRoute
  AuthenticatedPlatformSettingsReportReasonsRoute: typeof AuthenticatedPlatformSettingsReportReasonsRoute
  AuthenticatedPlatformSettingsServiceCategoriesRoute: typeof AuthenticatedPlatformSettingsServiceCategoriesRoute
  AuthenticatedReportsIdRoute: typeof AuthenticatedReportsIdRoute
  AuthenticatedReviewsIdRoute: typeof AuthenticatedReviewsIdRoute
  AuthenticatedUsersIdRoute: typeof AuthenticatedUsersIdRoute
  AuthenticatedVerificationsIdRoute: typeof AuthenticatedVerificationsIdRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedAuditLogsIndexRoute: typeof AuthenticatedAuditLogsIndexRoute
  AuthenticatedBookingsIndexRoute: typeof AuthenticatedBookingsIndexRoute
  AuthenticatedChatLogsIndexRoute: typeof AuthenticatedChatLogsIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedJobPostsIndexRoute: typeof AuthenticatedJobPostsIndexRoute
  AuthenticatedPlatformSettingsIndexRoute: typeof AuthenticatedPlatformSettingsIndexRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
  AuthenticatedReviewsIndexRoute: typeof AuthenticatedReviewsIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedVerificationsIndexRoute: typeof AuthenticatedVerificationsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRouteRoute: AuthenticatedAccountRouteRouteWithChildren,
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedBookingsIdRoute: AuthenticatedBookingsIdRoute,
  AuthenticatedChatLogsIdRoute: AuthenticatedChatLogsIdRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedPlatformSettingsAnnouncementsRoute:
    AuthenticatedPlatformSettingsAnnouncementsRoute,
  AuthenticatedPlatformSettingsNotificationTemplatesRoute:
    AuthenticatedPlatformSettingsNotificationTemplatesRoute,
  AuthenticatedPlatformSettingsReportReasonsRoute:
    AuthenticatedPlatformSettingsReportReasonsRoute,
  AuthenticatedPlatformSettingsServiceCategoriesRoute:
    AuthenticatedPlatformSettingsServiceCategoriesRoute,
  AuthenticatedReportsIdRoute: AuthenticatedReportsIdRoute,
  AuthenticatedReviewsIdRoute: AuthenticatedReviewsIdRoute,
  AuthenticatedUsersIdRoute: AuthenticatedUsersIdRoute,
  AuthenticatedVerificationsIdRoute: AuthenticatedVerificationsIdRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedAuditLogsIndexRoute: AuthenticatedAuditLogsIndexRoute,
  AuthenticatedBookingsIndexRoute: AuthenticatedBookingsIndexRoute,
  AuthenticatedChatLogsIndexRoute: AuthenticatedChatLogsIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedJobPostsIndexRoute: AuthenticatedJobPostsIndexRoute,
  AuthenticatedPlatformSettingsIndexRoute:
    AuthenticatedPlatformSettingsIndexRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
  AuthenticatedReviewsIndexRoute: AuthenticatedReviewsIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedVerificationsIndexRoute: AuthenticatedVerificationsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClerkauthRouteRouteChildren {
  ClerkauthSignInRoute: typeof ClerkauthSignInRoute
  ClerkauthSignUpRoute: typeof ClerkauthSignUpRoute
}

const ClerkauthRouteRouteChildren: ClerkauthRouteRouteChildren = {
  ClerkauthSignInRoute: ClerkauthSignInRoute,
  ClerkauthSignUpRoute: ClerkauthSignUpRoute,
}

const ClerkauthRouteRouteWithChildren = ClerkauthRouteRoute._addFileChildren(
  ClerkauthRouteRouteChildren,
)

interface ClerkAuthenticatedRouteRouteChildren {
  ClerkAuthenticatedUserManagementRoute: typeof ClerkAuthenticatedUserManagementRoute
}

const ClerkAuthenticatedRouteRouteChildren: ClerkAuthenticatedRouteRouteChildren =
  {
    ClerkAuthenticatedUserManagementRoute:
      ClerkAuthenticatedUserManagementRoute,
  }

const ClerkAuthenticatedRouteRouteWithChildren =
  ClerkAuthenticatedRouteRoute._addFileChildren(
    ClerkAuthenticatedRouteRouteChildren,
  )

interface ClerkRouteRouteChildren {
  ClerkauthRouteRoute: typeof ClerkauthRouteRouteWithChildren
  ClerkAuthenticatedRouteRoute: typeof ClerkAuthenticatedRouteRouteWithChildren
}

const ClerkRouteRouteChildren: ClerkRouteRouteChildren = {
  ClerkauthRouteRoute: ClerkauthRouteRouteWithChildren,
  ClerkAuthenticatedRouteRoute: ClerkAuthenticatedRouteRouteWithChildren,
}

const ClerkRouteRouteWithChildren = ClerkRouteRoute._addFileChildren(
  ClerkRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ClerkRouteRoute: ClerkRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authLoginRoute: authLoginRoute,
  authOtpRoute: authOtpRoute,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
